COLUMNS_10MIN = [
    "station_pressure",
    "sea_level_pressure",
    "precipitation",
    "temperature",
    "relative_humidity",
    "mean_ws",
    "mean_wd",
    "instantaneous_ws",
    "instantaneous_wd",
    "sunshine_hours",
]

COLUMNS_HOURLY = [
    "station_pressure",
    "sea_level_pressure",
    "precipitation",
    "temperature",
    "dew_point",
    "water_vapor_pressure",
    "relative_humidity",
    "mean_ws",
    "mean_wd",
    "sunshine_hours",
    "global_solar_radiation",
    "snow_fall",
    "snow_depth",
    "cloud_cover",
    "visibility",
]

COLUMNS_DAILY = [
    "mean_station_pressure",
    "mean_sea_level_pressure",
    "total_precipitation",
    "max_hourly_precipitation",
    "max_10min_precipitation",
    "mean_temperature",
    "highest_temperature",
    "lowest_temperature",
    "mean_relative_humidity",
    "min_relative_humidity",
    "mean_ws",
    "max_ws",
    "max_wd",
    "max_instantaneous_ws",
    "max_instantanious_wd",
    "most_frequent_wd",
    "sunshine_hours",
    "total_snow_fall",
    "max_snow_depth",
    "daytime_general_weather_condition",
    "nighttime_general_weather_condition",
]
